source_roots = [
    "apps/api/src",
    "apps/db/src",
    "libs/db/src",
    "libs/listings/src",
    "libs/repository/src",
    "tools/scraper/src",
]
forbid_circular_dependencies = true
ignore_type_checking_imports = false

exclude = [
    "**/__pycache__",
    "**/tests/**",
    ".venv/**",
    "apps/db/alembic/**",
]

[rules]
unused_ignore_directives = "error"
